# -----------------------------------------------------------------------------
# 사이트 필수 기본 정보
# -----------------------------------------------------------------------------
name: K-Contents Hub
title: K-Contents Hub
description: K-Contents Hub shares in-depth K-POP analysis, music video breakdowns, artist insights, and Korean culture stories in English for global fans who want to explore trends and discover hidden meanings.
url: "https://kcontents.site"
baseurl: ""
locale: "en-US"
timezone: Asia/Seoul

# -----------------------------------------------------------------------------
# 테마 설정 (충돌 방지를 위해 null 로 설정)
# -----------------------------------------------------------------------------
theme: null

# -----------------------------------------------------------------------------
# 빌드 및 퍼머링크 설정
# -----------------------------------------------------------------------------
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 6
paginate_path: /page:num/

# 마크다운 렌더링 설정
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

# -----------------------------------------------------------------------------
# 플러그인 목록
# -----------------------------------------------------------------------------
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# -----------------------------------------------------------------------------
# 제외 파일 목록
# -----------------------------------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
