remote_theme: "mmistakes/minimal-mistakes@4.24.0"

title: K-Contents Hub
description: K-Contents Hub shares K-POP, and Korean culture in English for global fans.
# url: 'https://kcontents.site' # 커스텀 도메인 쓰면 주석 해제

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache   # ← 추가 (MM 필수/권장)
  - jekyll-sitemap
  - jekyll-paginate        # ← 그대로 OK (v1)
  # - jekyll-archives      # ← 제거 (GitHub Pages 기본 빌드 미지원)
