name: K-Contents Hub
description: K-Contents Hub shares K-POP, and Korean culture in English for global fans.

url: "https://kcontents.site"
baseurl: ""

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-feed