# -----------------------------------------------------------------------------
# 사이트 필수 기본 정보
# -----------------------------------------------------------------------------
name: K-Contents Hub
title: K-Contents Hub
description: K-Contents Hub shares K-POP, and Korean culture in English for global fans.
url: "https://kcontents.site" # 사용하시는 실제 도메인
baseurl: ""
locale: "en-US" # 영문 블로그에 맞춰 수정됨
timezone: Asia/Seoul

# -----------------------------------------------------------------------------
# 테마 설정
# -----------------------------------------------------------------------------
theme: jekyll-theme-minimal # ⬅️ Minimal 테마 적용 (theme 사용)

# -----------------------------------------------------------------------------
# 빌드 및 퍼머링크 설정
# -----------------------------------------------------------------------------
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate: 5
paginate_path: /page:num/

# 마크다운 렌더링 설정
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

# -----------------------------------------------------------------------------
# ⚠️ 플러그인 목록 정리 (Minimal 테마는 복잡한 플러그인이 필요 없습니다)
# -----------------------------------------------------------------------------
plugins:
  - jekyll-sitemap # SEO를 위해 유지
  - jekyll-feed    # RSS 피드를 위해 유지
  - jekyll-paginate # 포스팅 목록 페이지네이션을 위해 유지
  - jekyll-seo-tag  # ✅ 이 줄을 추가하세요

# -----------------------------------------------------------------------------
# 소셜/푸터 링크 설정
# -----------------------------------------------------------------------------
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/khslam72/khslam72.github.io"
    - label: "RSS"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"

# -----------------------------------------------------------------------------
# 제외 파일 목록
# -----------------------------------------------------------------------------
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME






