name: K-Contents Hub
description: K-Contents Hub shares K-POP, and Korean culture in English for global fans.

avatar: /images/site%20icon.png

footer-links:
  github: barryclark/jekyll-now
  twitter: jekyllrb
  rss:

disqus:
google_analytics:

url: "https://kcontents.site"
baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

theme: jekyll-theme-cayman

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME