#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: K-Contents Hub

# Short bio or description (displayed in the header)
description: K-Contents Hub shares K-POP, and Korean culture in English for global fans.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/site%20icon.png

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: barryclark/jekyll-now
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: jekyllrb
  stackoverflow:
  youtube:
  googleplus:

# Enter your Disqus shortname (not your username) to enable commenting on posts
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-xxxxxx-x)
google_analytics:

# Your website URL (e.g. http://yourusername.github.io)
url:

# If you're hosting in a project repository, set baseurl ("/repo-name"), otherwise keep empty
baseurl: ""

permalink: /:title/

version: v1.2.0

# Markdown processor
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass settings
sass:
  style: :expanded

# Plugins (replace gems: with plugins:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme

# Exclude these files from production build
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Remote theme
remote_theme: "Phlow/feeling-responsive"