name: Submit URLs to Google Indexing API

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Select URLs to index"
        required: true
        type: choice
        options:
          - today
          - yesterday
          - manual
      manual_urls:
        description: "Manual mode: Enter URLs separated by spaces"
        required: false
        default: ""

jobs:
  indexing:
    runs-on: ubuntu-latest
    env:
      TZ: "Asia/Seoul"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Activate gcloud SDK session
        run: |
          gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}

      - name: Determine URLs to index
        id: get_urls
        run: |
          MODE="${{ github.event.inputs.mode }}"
          URLS=""

          if [ "$MODE" == "today" ]; then
            FILES=$(find _posts -type f -mtime -1)
          elif [ "$MODE" == "yesterday" ]; then
            FILES=$(find _posts -type f -mtime 1)
          elif [ "$MODE" == "manual" ]; then
            URLS="${{ github.event.inputs.manual_urls }}"
          fi

          for file in $FILES; do
            FILENAME=$(basename "$file" .md)
            TITLE_PART=$(echo "$FILENAME" | cut -d'-' -f4-)
            URL="https://kcontents.site/${TITLE_PART}/"
            URLS="$URLS $URL"
          done

          echo "URLs to index: $URLS"
          echo "URLS_TO_INDEX=$URLS" >> $GITHUB_ENV

      - name: Submit URLs to Google Indexing API
        if: env.URLS_TO_INDEX != ''
        run: |
          for url_to_index in ${{ env.URLS_TO_INDEX }}; do
            echo "Submitting: $url_to_index"
            ACCESS_TOKEN=$(gcloud auth print-access-token)
            RESPONSE_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              -X POST "https://indexing.googleapis.com/v3/urlNotifications:publish" \
              -H "Authorization: Bearer ${ACCESS_TOKEN}" \
              -H "Content-Type: application/json" \
              --data "{ \"url\": \"$url_to_index\", \"type\": \"URL_UPDATED\" }")

            if [ "$RESPONSE_CODE" -eq 200 ]; then
              echo "✅ Successfully submitted: $url_to_index"
            else
              echo "❌ Error submitting: $url_to_index (Response code: $RESPONSE_CODE)"
            fi
          done
